### ISSUE TITLE
Kisebb UI hiba bizonyos készülékeken

### ISSUE THREAD

**Issue by hubabuba100** [filc/naplo#10]
Bizonyos készülékeken a profil buborék valamennyire belelóg az aktuális óra widgetbe. A képernyőkép egy Galaxy S10-en készült. Az én készülékemen (Huawei P Smart 2019) a hiba nem áll fenn. 
Filc verzió: 3.0.1
![received_523501118742226](https://user-images.githubusercontent.com/57961209/132177531-c54573d6-1f1c-4d34-924f-9972e1d399cc.jpeg)

**Comment by 55nknown** [comment]
Köszönjük a jelentést!

**Comment by 55nknown** [comment]
javitva
