### ISSUE TITLE
[pr] Egyéni színek / Custom colors

### ISSUE THREAD

**Issue by Zan1456** [filc/naplo#111]
![IMG_20220901_183631](https://user-images.githubusercontent.com/62830223/187968741-d9628fa6-b7c2-4e54-b5b5-9f8529425a06.jpg)
![IMG_20220901_184025](https://user-images.githubusercontent.com/62830223/187968747-c9397d09-f0d7-46a1-b9cd-d024dc5ddeaa.jpg)

**Comment by 55nknown** [comment]
kesz
