### ISSUE TITLE
Akadozások a v3.3.3-ban

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#114]
Eszköz: OnePlus 8
Android 12
Apróbb, de annál inkább zavaró, szüntelen akadozások az appban.

**Comment by 55nknown** [comment]
Eddig nem tapasztaltál ilyet?

**Comment by d4f5409d** [comment]
Pontosan ahogy írod, nem. Ez v3.3.3-as. Görgetés közben lehet igazán látni.

**Comment by 55nknown** [comment]
Azt esetleg el tudnád árulni nekünk, hogy milyen készüléket használsz?

**Comment by 55nknown** [comment]
Ez igazán furcsa, ugyanis én nem tapasztaltam ilyet, pedig gyengébb telefonom is van és ráadásul 120 Hz-en fut, amit az app nekem tart is stabilan.

**Comment by d4f5409d** [comment]
Megpróbálnád kiszedni, amit anno berakattam veletek fps fixként (oneplus 90 fps flutter fix vagy mi) és úgy elküldeni itt egy debug apkot zipként, hogy tujdam tesztelni, az-e a probléma?

**Comment by 55nknown** [comment]
Nem hinném hogy azzal lenne a probléma

**Comment by d4f5409d** [comment]
Update: az about pageben nem látok akadozást, ott tökelétesen működik. Ahogy észrevettem, ott akadozik csak ahol sok mindent kell megjelenítenie. Meg tudnátok nézni?
