### ISSUE TITLE
Új ikonok picit balls

### ISSUE THREAD

**Issue by rageboi1011** [filc/naplo#115]
Nem szeretnék úgy hallatszani mint egy tőgyökeres paraszt, de szerintem nincs más mód arra hogy ezt tegyem, az új ikonok picit bénán néznek ki. Bármelyik előző iconpack amelyet használtatok jobban nézett ki, nemcsak azért mert egyszerűen csak jobb a design, hanem az ikonok összefüggenek. A mostani iconokból a biosz be van töltve, semelyik más nincs, egyik kerekített, másik pedig csak körvonalas, és sokkal amatőrebbnek néz ki tőle az alkalmazás. Megint bocsánat hogy így hangzok, de nincs kedvem szebben tenni már alapból hosszú ez az issue.

**Comment by 55nknown** [comment]
Az új ikonok oka az volt, hogy iOS-en implementáltuk a Live Activities featuret, viszont iOS natívban sokkal egyszerűbb a cupertino ikonokat használni, mivel azok már alapból a rendszer részei. Megoldásként egy ikon testreszabhatási lehetőséget tudnék elképzelni.

**Comment by rageboi1011** [comment]
ja, de Androidról beszélek. Ott talán alapból lehetne pl material.

**Comment by 55nknown** [comment]
fixed
