### ISSUE TITLE
(jobban) Testreszabható szünet és óra idők

### ISSUE THREAD

**Issue by rageboi1011** [filc/naplo#116]
Elég egyszerű ötlet, nem minden iskolában és osztályban pontosan ugyanannyira hosszúak a szünetek, ezért jó lenne egy beállítás arra hogy egyesével beállíthassuk a szüneteket.

-

Új propozíció ha nem vert át a válaszoló személy, óránként offset beállítás, és ha véletlen megváltozna egy óra ideje pl egy lementett alaphoz képest, felülírja az előző órát az újra

**Comment by thegergo02** [comment]
Ezt a KRÉTA adja meg (általában).

**Comment by rageboi1011** [comment]
> Ezt a KRÉTA adja meg (általában).

oh hát az gigafos

**Comment by 55nknown** [comment]
Nem értem, mi értelme lenne pontosan annak, ha be tudnád állítani a szünetek idejét, amikor az kiszámítható az órák kezdetéből és végéből?

**Comment by rageboi1011** [comment]
nekem valamiért helytelen

**Comment by 55nknown** [comment]
Akkor valószínűleg inkább az iskolád titkárságát kell keresned ezzel a problémával, ugyanis ez a Filctől egy független probléma.

**Comment by rageboi1011** [comment]
👌
