### ISSUE TITLE
A jelenlegi óra nem jelenik meg iOS-en

### ISSUE THREAD

**Issue by BBence00** [filc/naplo#117]
Az értesítés és a Live Activities is engedélyezve van a Filcnek, mégse jelenik meg a zárképernyőn a jelenlegi óra.
Vagy csak a Dynamic Island van támogatva jelenleg az appban? Ha igen, megoldható-e Dynamic Island nélküli készülékeken, hogy Live Activity formájában megjelenjen a zárképernyőn is?

**Comment by 55nknown** [comment]
Elméletileg javítva, kérlek jelezz vissza a következő frissítés alkalmával. Köszi a türelmet!
