### ISSUE TITLE
Surprise grades-et nem lehet kikapcsolni

### ISSUE THREAD

**Issue by thegergo02** [filc/naplo#118]
A legújabb (v3.3.4) verzióban a surprise grades kapcsolót ha kikapcsolom, akkor még mindig nem jelenik meg a jegyem viszont nem is jön be az animáció (azaz, nem tudom az értékelést megnézni).

**Comment by ezyyeah** [comment]
> A legújabb (v3.3.4) verzióban a surprise grades kapcsolót ha kikapcsolom, akkor még mindig nem jelenik meg a jegyem viszont nem is jön be az animáció (azaz, nem tudom az értékelést megnézni).

kovetkezo verzioban javitva lesz
