### ISSUE TITLE
Órarend megnyitáskor nem mai napon nyílik meg

### ISSUE THREAD

**Issue by RedyAu** [filc/naplo#119]

**Comment by RedyAu** [comment]
Kéne egy szavazás arról is hogy hét váltáskor mi a legjobb:
 - Azonos napon maradni
 - Hétfőre váltani
 - Egyéb

**Comment by RedyAu** [comment]
When fixing don't forget https://github.com/filc/naplo/issues/43

**Comment by UnknownPlayer78** [comment]
actuall nem befolyasolja #43-t, fixed
