### ISSUE TITLE
Átugorható bevezetések

### ISSUE THREAD

**Issue by Kristof120701** [filc/naplo#120]
Jó lenne ha egy skippel át lehetne ugrani az app telepítéskor a bevezetőket, tehát a bejelentkezési képernyő előttit és az utána lévőt is.

**Comment by RedyAu** [comment]
Bár két külön skippel, de mindkét említett dolog átugorható, a tutorialképernyők meg is fognak újulni. Így ez egy wontfix, bocsi.
