### ISSUE TITLE
App updates over mobile data

### ISSUE THREAD

**Issue by Zsigio** [filc/naplo#122]
Hi,

Today I was rather annoyed to find that Filc has just downloaded a 400 megabyte update over mobile data. I don't have a huge data plan, so I'd appreciate if you'd include a feature to at least show a prompt before it updates itself over cell.

Aside from that, I have absolutely no complaints, you do really put a lot of effort into this app, and it shows <3

**Comment by 55nknown** [comment]
Appreciate the feedback, and thanks for the idea!
