### ISSUE TITLE
Hosszú jelszó

### ISSUE THREAD

**Issue by pcmester** [filc/naplo#123]
Sziasztok!

Valamiért a 100 karakterhossz feletti kisbetűt, nagybetűt, számokat és speciális karaktereket tartalmazó jelszavakat nem fogadja el az app. A webes felületen működik.

**Comment by RedyAu** [comment]
A hivatalos Kréta Tanulóknak appba be tudsz vele jelentkezni?

**Comment by pcmester** [comment]
Nem. Ezek szerint ez valami API korlátozás lehet? 🤔

**Comment by RedyAu** [comment]
Valószínűleg az lesz akkor, igen. Írj bátran a Kréta ügyfélszolgálatának, ha a Filcet nem említed, szívesen fognak segíteni, lehet hogy még javítják is :D
Ezt most zárom.

**Comment by pcmester** [comment]
Ez még mindig Magyarország... Azt a választ kaptam, hogy cseréljem le egy rövidebb jelszóra :)
