### ISSUE TITLE
Igazolatlan hiányzások száma helytelen 

### ISSUE THREAD

**Issue by rageboi1011** [filc/naplo#129]
vajon mi lehet a probléma 

Lehetséges azért, mivel a hiányzás igazoltságánál sem az van írva hogy igazolt, se az hogy nem. Lehet hogy általában is így működik, de nem néztem még soha netes krétában hiányzást ez előtt.

![Screenshot_20221117_095914](https://user-images.githubusercontent.com/60071448/202403057-3d8ed2f9-dd4e-4c7c-9b13-21a53866e178.png)

**Comment by rageboi1011** [comment]
![Screenshot_20221117_095914](https://user-images.githubusercontent.com/60071448/202403057-3d8ed2f9-dd4e-4c7c-9b13-21a53866e178.png)

**Comment by rageboi1011** [comment]
nagyon szeretem a jól dizájnolt felületeket

**Comment by 55nknown** [comment]
Az az egy óra "igazolandó" tehát még nincs eldöntve hogy igazolt vagy igazolatlan, ezért az app működése helyes.

**Comment by rageboi1011** [comment]
> Az az egy óra "igazolandó" tehát még nincs eldöntve hogy igazolt vagy igazolatlan, ezért az app működése helyes.

oh el is felejtettem hogy olyan 2 hét van igazolni hiányzásokat
