### ISSUE TITLE
Premium ad on home screen has a weirdly looping anim

### ISSUE THREAD

**Issue by xoudoesthings** [filc/naplo#133]
https://user-images.githubusercontent.com/97404131/202928177-3c913bf5-e099-4e77-8044-3ff9f55c7dd6.mp4

It works fine in settings.

**Comment by dikahdoff** [comment]
weird, it works correctly for me

i was thinking of battery saver, but it still works right with that enabled

**Comment by 55nknown** [comment]
it will be "removed"
