### ISSUE TITLE
Összezavarodik a világos és sötét téma

### ISSUE THREAD

**Issue by Gbr22** [filc/naplo#136]
Akkor történik ha törlöm a profilt, majd egyből újra belépek. Az app újraindítása megoldja.
![image](https://user-images.githubusercontent.com/25722827/106742701-aa2b9600-661d-11eb-98e7-9f1f393266c8.png)
![image](https://user-images.githubusercontent.com/25722827/106743177-540b2280-661e-11eb-8a7a-7b4fd2f2abfb.png)

**Comment by RedyAu** [comment]
#125
