### ISSUE TITLE
`Get Premium` btn translation missing

### ISSUE THREAD

**Issue by szalovszky** [filc/naplo#141]
![Screenshot_20221120-235022_Filc_Naplo_1](https://user-images.githubusercontent.com/29980128/202930859-568cdb49-3a7a-4dff-87aa-970d3e6d2b05.png)
![Screenshot_20221120-235005_Filc_Naplo_1](https://user-images.githubusercontent.com/29980128/202930862-ff5ea2af-e42b-4741-a9b2-150b0b57ae27.png)

**Comment by 55nknown** [comment]
how would you translate it

**Comment by szalovszky** [comment]
to german im not sure but to hungarian, maybe: "Prémium beszerzése"

**Comment by 55nknown** [comment]
that sounds a little odd doesn't it

**Comment by szalovszky** [comment]
Discord does the same
![discord](https://user-images.githubusercontent.com/29980128/203059086-479386ae-665c-4e82-978d-7a7a7d2fe827.png)

**Comment by 55nknown** [comment]
meh

**Comment by szalovszky** [comment]
And Discord does this for german
![discord_de](https://user-images.githubusercontent.com/29980128/203059717-25ac1880-c20a-4a39-8cb8-c5567afbc763.png)

**Comment by 55nknown** [comment]
sure enough

**Comment by xoudoesthings** [comment]
or just write "filc premium" and then problem solved

**Comment by 55nknown** [comment]
yes good
