### ISSUE TITLE
Több fiók

### ISSUE THREAD

**Issue by FayVince** [filc/naplo#144]
Több fiókom van és akkor, amikor bezárom az apppot és megnyitom újra, kitörlődik az utolsó fiók. + lehet, hogy csak a telefonom rossz, de ha több fiók van, akkor a legfelsőknél eltűnnek a hiányzások százalékai.

**Comment by 55nknown** [comment]
Melyik verziót használod?

**Comment by FayVince** [comment]
3.4.1
3.4.0 előtt nem törlődtek

**Comment by FayVince** [comment]
Letöröltem, és letöltöttem a 3.4.2-t és visszajöttek a fiókok. Thx

**Comment by efi99** [comment]
Nálam a 3.4.2-re való frissítés után a 3 felhasználóból eltűnt 2, újra hozzá kellett adni őket.

**Comment by FayVince** [comment]
Érdekes, hiába törlöm a fiókókat, újratelepítés után ott maradnak. De 3.4.1 előtt nem látszanak. Ha hozzáadok egy fiókot az is eltűnik.

**Comment by 55nknown** [comment]
Megtaláltam a problémát és javítottam is, következő frissítéstől helyre fog állni.
