### ISSUE TITLE
Grades timespan switcher lightmode bug

### ISSUE THREAD

**Issue by xoudoesthings** [filc/naplo#145]
![Screenshot_20221122-104242.png](https://user-images.githubusercontent.com/97404131/203280677-f6de1f62-e5bf-4f3b-9f18-61f1cc08624e.png)

**Comment by 55nknown** [comment]
who uses light mode >:c

**Comment by xoudoesthings** [comment]
me during the day so i can actually read it

**Comment by 55nknown** [comment]
fixed
