### ISSUE TITLE
Use external browser in About section

### ISSUE THREAD

**Issue by YMSTNT** [filc/naplo#146]
Jelenleg a Névjegynél minden link egy fura in-app browserben nyílik meg, ahelyett hogy az app passzolná a linket külső alkalmazásoknak.

Ez unintentional viselkedéshez vezet, pl. a Discord invite link nem működik rendesen.
![Screenshot_20221124-083105_Filc Napló.png](https://user-images.githubusercontent.com/21342713/203725958-464c467a-e064-4975-a3b7-1246c4dc6585.png)

A többinél is jó lenne, ha külső böngészőben nyílnának meg a linkek, mert így megnyílhatnak olyan appokban, amik tudnak linket kezelni.

Így például:

- A Discord invite megnyílhatna a Discord appban és a user el tudja fogadni az inviteot.
- A Github repo link megnyílhatna a Github appban és a user tud nyitni issuet, starolni a repot, kódot böngészni stb.
- Még a Filc weboldala is megnyílhatna normális böngészóben (vagy akár Chrome Custom Tabban), így a user tudja böngészni az oldalt úgy, mint a többi oldalt, és ki tudja másolni a linket, megosztani stb.

**Comment by d4f5409d** [comment]
Az ok, ha nekem még mindig az internalban nyílik meg?

**Comment by YMSTNT** [comment]
Igen, mert azóta az app nem kapott frissítést
