### ISSUE TITLE
Az elementek lerenderelését optimalizálni

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#151]
>Update: az about pageben nem látok akadozást, ott tökelétesen működik. Ahogy észrevettem, ott akadozik csak ahol sok mindent kell megjelenítenie. Meg tudnátok nézni? 
OnePlus 8 (immáron) Android 13

_Originally posted by @d4f5409d in https://github.com/filc/naplo/issues/114#issuecomment-1404288812_

Rájöttem tesztelések alkalmával, hogy amikor nem jelenít meg sok elemet a Filc, egyáltalán nincs akadozás, pont mint v3.3.3 előtt. Ha tudnánk optimalizálni a renderelését az elemeknek (pl. jegyek, órák), szerintem megszűnne az akadozás mindenhol.

Android 13, OnePlus8

**Comment by d4f5409d** [comment]
Megszűnt a hiba, lezárom készként.

**Comment by 55nknown** [comment]
remek köszi
