### ISSUE TITLE
Filc Premium fizetési módok bővítése

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#153]
Lehetne előfizetni ún. "harmadik fél" segítségével pl. Barion-nal vagy kriptovalutákkal (BTC, XMR, stb.)

Az indok az az, hogy a Github fiókomat nem szeretném összekötni a világi identitásommal. (Egyrészt mert Microsoft által van birtokolva)

**Comment by 55nknown** [comment]
sajnáljuk de jelenleg nem áll módunkban kibővíteni a fizetési lehetőségeket. ha nagyon hiányzik a prémium tagelj meg Discordon.

**Comment by d4f5409d** [comment]
> sajnáljuk de jelenleg nem áll módunkban kibővíteni a fizetési lehetőségeket. ha nagyon hiányzik a prémium tagelj meg Discordon.

Nincs discordom :(
Viszont a publikus kulcsomat tudom csatolni ha az is megfelelne

**Comment by d4f5409d** [comment]
Srácok tényleg kellene 💀😅

**Comment by 55nknown** [comment]
fogadd sok szeretettel bokezu ajandekom

**Comment by d4f5409d** [comment]
> fogadd sok szeretettel bokezu ajandekom

Nagyon szépen köszönöm, így most szereztetek egy nagyon lojális közremüködőt, azaz megvettetek kilóra 😂

Megy az app promó mindenhova💯
