### ISSUE TITLE
Csak az elmúlt 30 nap házijait töltse le

### ISSUE THREAD

**Issue by RedyAu** [filc/naplo#153]
Az indításkori szinkronizálásnál nagyon sokáig tart a házik betöltése, elég lenne a lekérésben az elmúlt 30 napot kérni.
Ha a user többet akar, akkor erre a korábbi házik listájának alján legyen lehetősége: Legyen ott egy "minden házi betöltése" gomb.

**Comment by RedyAu** [comment]
Valamint valószínűleg a Kréta sem örül neki hogy minden egyes Filc indításkor 250 nap 1000+ háziját kérik le a userek.

**Comment by DarK-rtfm** [comment]
Jelenleg is csak az elmúlt 1 hónapot tölti le. Azért lassú, mert elösször letölti egyben a hónapnyi házit, majd ebből a listából az ID-k alapján letölti az összeset egyesével, hogy a csatolmányhoz tartozó infó is lejöjjön hozzá.

**Comment by RedyAu** [comment]
Well gtk. Mikor múltkor néztem akkor konkrétan unix epochtól now-ig kérte
le a házikat.
De a tartalom letöltés elég a legutóbbi 7 napnál is.
