### ISSUE TITLE
Különleges "lezáró" jegyek kezelése - Jegyoldali lenyíló menü

### ISSUE THREAD

**Issue by Balint66** [filc/naplo#156]
Az osztályozóval szerzett jegyeket nem tudja kezelni az applikáció.

`RangeError (index): Index out of range: index should be less than 7: 7`

```logs
#0      Iterable.elementAt (dart:core/iterable.dart:585:5)
#1      CustomTabIndicator.build (package:filcnaplo/ui/common/custom_tabs.dart:104:26)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
```

**Comment by RedyAu** [comment]
Ezt valahogy szép ui-al is le kéne kezelni
Vagy csak simán univerzálisra csináljuk a lezárt jegyeket?

**Comment by RedyAu** [comment]
#155
