### ISSUE TITLE
Type error with graphs somehow? (version 2.1.5)

### ISSUE THREAD

**Issue by RedyAu** [filc/naplo#163]
```dart
    List<Evaluation> data = widget.data
        .where((evaluation) => evaluation.value.weight != 0)
        .where((evaluation) => evaluation.type == EvaluationType.midYear)
        .where((evaluation) => evaluation.evaluationType.name == "Osztalyzat")
        .toList();
```

`Unsupported operation: Infinity or NaN toInt`

```
#0      _Double.toInt (dart:core-patch/double.dart:219)
#1      _Double.floor (dart:core-patch/double.dart:183)
#2      _SubjectGraphState.build (package:filcnaplo/ui/pages/evaluations/subjects/graph.dart:27)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4684)
```

Az egyetlen kérdés az, hogy a lista assignolás mikor csinál toInt-et? a bemásolt kódblokk első sorára mondja a hibát, bár lehet hogy a tördelt, de egy sorba tartozó dolgok miatt bármelyikkel (mondjuk a toListtel) is lehet a gond.

**Comment by RedyAu** [comment]
Ééés igen, a weight double, abból int lesz komparáláskor. Már csak a problémát kell megtalálni.

**Comment by RedyAu** [comment]
Aktchually d510d0572d14de27bb527e72958561f27b0ff348
_maybe_
_reopen if issue persists after 2.1.6_

**Comment by DarK-rtfm** [comment]
[actually](https://github.com/filc/naplo/commit/8a2ec85a0d4354aee375ca9fd0c38804abfb64b3)
