### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by t-gergely** [filc/naplo#21]
Mi a helyzet az [f-droidos terjesztéssel](fdroidrepos://filcnaplo.hu/fdroid/repo/)? A legújabb verzió ott 2.1.5 (lastupdated:1981-01-01), és nem lehet vele belépni, amint a release notesból is kiderül.

**Comment by RedyAu** [comment]
F-Droid már nem támogatott. Töltsd le az appot Playből vagy magát az apk-t. Tartalmaz automata frissítőt.

**Comment by t-gergely** [comment]
Kár. Azt lehet tudni, hogy miért nem? Ezeket a lapokat hozzá kellene igazítani a támogatáshoz:
https://filcnaplo.hu/dmca/
https://filcnaplo.hu/downloads/

**Comment by RedyAu** [comment]
Az F-Droidnak akkor volt értelme, amikor még nem volt automata frissítő az appban, annak a helyettesítésére. A hivatalos F-Droid tárban lenne értelme fenn lenni (rá lehetne találni az appra), de saját repót fenntartani nincs értelme, nem éri meg az energiát.
Az issuet átnevezem az említett dolgok frissítésére.

**Comment by t-gergely** [comment]
Így van, a hivatalos tárra gondoltam, "forrás" terjesztéssel.

**Comment by RedyAu** [comment]
A hivatalos tárban afaik sosem voltunk fenn, nem is elvünk ennyire szigorúan a FOSShoz tartani magunkat, nem biztos hogy felkerülnénk/fennmaradnánk.
