### ISSUE TITLE
Az app kifagy a jegyek tab megnyitásakor

### ISSUE THREAD

**Issue by Botond08** [filc/naplo#22]
Filc v3.0.4

Ezt lehet belőle érzékelni:
![Screenshot_20210921-094845.jpg](https://user-images.githubusercontent.com/31571293/134133439-8b117b24-9303-4e34-86fe-6d04489dbf1e.jpg)

A telefon egy Oneplus 7t Pro. Az alap adatok róla:
![Screenshot_20210921-095212.jpg](https://user-images.githubusercontent.com/31571293/134133577-5d46fba1-4278-4d5d-9b5c-dbf8e2662d9b.jpg)

~~Kipróbáltam egy Xiaomi Mi 9 SE-n is Android 10, MIUI 12.0.4 alatt és ott ez a probléma nem jött elő.~~
Edit: Refresh-nél a Mi 9 SE-nél is kifagy

**Comment by Botond08** [comment]
Update: Refresh-nél a Mi 9 SE-nél is kifagy

**Comment by leventehodi** [comment]
Ugyanez nálam is 3.0.3-al

**Comment by 55nknown** [comment]
fixed in theory
