### ISSUE TITLE
Bad element a jegyek tab megnyitásakor

### ISSUE THREAD

**Issue by BlueWoIf** [filc/naplo#24]
Valószínűleg amiatt van mert van egy olyan beírt dolgozat jegy, amire nem kaptam értékelést, de csak egy tipp.

https://user-images.githubusercontent.com/47600010/134322610-c1d568b3-b33c-47f2-a4cc-48d1e61e3e83.mp4

**Comment by 55nknown** [comment]
Légszíves frissíts az új verzióra és küldj hibajelentést!

**Comment by 55nknown** [comment]
Köszönjük a hibajelentést, javítani fogjuk!

**Comment by 55nknown** [comment]
fixed
