### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#27]
Change analytics option from opt-in default value, to opt-out default.

**Comment by 55nknown** [comment]
Sokat gondolkoztunk ezen, de vegul arra jutottunk, hogy mivel semmi olyat nem gyujtunk ami kozel szemelyes adat lenne stb. es egyebkent ha playen keresztul toltod le akkor ezeket, sot ennel meg tobb adatot is kapnank, ezert teljesen elfogadhato. Az osszes adat az a telefon operacios rendszerenek a neve pl. Android/iOS es a telepitett verzio.

**Comment by 55nknown** [comment]
Ilyen arcodba nyomulos bekapcsolasert konyorgos popupot meg nem toleralok
