### ISSUE TITLE
Add 90 and 120 FPS support

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#28]

**Comment by 55nknown** [comment]
Tudnal egy kicsit reszletesebb leirast adni? Ha jol ertem akkor a 90, ill 120 Hz kepes telefonokon alapbol 60 Hz-ra van limitelve az app. Nem lehet esetleg ezt valamilyen beallitassal szabalyozni?

**Comment by d4f5409d** [comment]
Nem. Az app határozza meg mennyi a limit, akkor is ha több FPS-re van állítva. Nem tudok semmit sem állítani rajta.

**Comment by 55nknown** [comment]
Sajnos nincs ilyen telefonom amivel tesztelni tudnam ugyhogy erre varnod kell.

**Comment by 55nknown** [comment]
Possible fix: <https://stackoverflow.com/questions/63631522/flutter-120fps-issue>
Esetleg kovetkezo frissitesben implementalom aztan meglatjuk, hogy javul-e.

**Comment by 55nknown** [comment]
3.0.6-os verzioban hozzaadtam a patchet, majd nezd meg kerlek, hogy megjavult-e

**Comment by d4f5409d** [comment]
Most már jól működik

**Comment by d4f5409d** [comment]
Megint előjött ez a bug.

**Comment by 55nknown** [comment]
En nem tapasztaltam
Nem lehet hogy valami app fuggo beallitas?

**Comment by 55nknown** [comment]
Azert szedtem ki a fixet mert nalam mukodott nelkule is

**Comment by d4f5409d** [comment]
Nem app függő beállítás. Nem megy a90 FPS a fix nélkül.

**Comment by 55nknown** [comment]
akkor szeretned hogy visszarakjam?

**Comment by RedyAu** [comment]
Nyilván szeretné xd

**Comment by 55nknown** [comment]
shh
