### ISSUE TITLE
Oldalváltás rezgés beállítások

### ISSUE THREAD

**Issue by 55nknown** [filc/naplo#3]
*todo: implement*

**Comment by Empire201** [comment]
Szia!

Nálam az alacsony rezgést nem érezni.

Készülék: Huawei P20 Lite
Android verzió: 9
Tesztelt verzió: 3.0 Stabil kiadás

**Comment by RedyAu** [comment]
Volt, aki meg arra panaszkodott, hogy túl hosszú, mert rezgésnek érződik, nem pedig "haptic feedbacknek". Ezért van a beállítás, állítsd magasabbra.
