### ISSUE TITLE
Fájlok a hazi feladatnál

### ISSUE THREAD

**Issue by zalnaRs** [filc/naplo#37]
A hazi feladathoz csatolt fájlok meg jelenitése.

**Comment by RedyAu** [comment]
Tudsz küldeni erről a háziról egy képernyőképet krétából?

**Comment by zalnaRs** [comment]
![Screenshot_20200918-192341_KRTA Tanulknak](https://user-images.githubusercontent.com/53659756/93626946-81935e80-f9e4-11ea-8b8f-8f3adafe94a6.jpg)

**Comment by UnknownPlayer78** [comment]
#80
