### ISSUE TITLE
Rezgések nem működnek

### ISSUE THREAD

**Issue by Empire201** [filc/naplo#38]
Üdv
Rezgések egyik frissítésről a másikra megszűnt. Mindegyik fokozatot néztem de nem jó.

**Comment by 55nknown** [comment]
Kedves Birodalom Kettőszázegy!

Sajnos a rezgés nagyban függ az eszközödtől, nagyon nehéz reprodukálni a hibát és ez a funkció nem élvez prioritást, így ezzel jó ideig egyáltalán nem tudunk foglalkozni. Ha nagyon hiányolod a rezgést, az Amazonon nagyon olcsó vibrátorokat lehet találni. A másik opció az, hogy egy KacsaKacsaMegy keresés alapján megtalálod azt az opciót a beállítások közt, ami lehetővé teszi a rezgést.
Tájékoztatjuk, hogy az Ügyfélszolgálat segítségének igénybevételéért 400 Ft/üzenet költséget számítunk fel, amelynek 0,01%-át a Magyar Vadászgörény Klubnak adományozzuk.

Üdvözlettel,
eFilc Informatikai Zrt. Ügyfélszolgálat

**Comment by Empire201** [comment]
Köszi a segítséget.....

**Comment by RedyAu** [comment]
Savage
