### ISSUE TITLE
Üzenetek törlése

### ISSUE THREAD

**Issue by cicomk** [filc/naplo#41]
Hiába archiválom az üzeneteket, ráfrissítek vagy ki-be lépek és újra megjelennek.

**Comment by RedyAu** [comment]
Ez a funkció még nincs kész, egy későbbi verzióban fog működni. Köszi a türelmet!

**Comment by cicomk** [comment]
Értem. Köszönöm a választ!

**Comment by UnknownPlayer78** [comment]
#80
