### ISSUE TITLE
HTML Szövegek másolhatósága

### ISSUE THREAD

**Issue by stsmurfy** [filc/naplo#46]
Roppant nagy segítség lenne, ha a Krétához hasonlóan a házik, üzenetek, feljegyzések, stb. szövegei kijelölhetőek és kimásolhatóak lennének. Elég gyakori eset így szülők közt, hogy egymásnak kell küldözgetni az anyagokat, mert épp nem akar Krétázni vagy nem megy neki, viszont nem a legjobb folyton képernyőképekkel teledobálni a beszélgetéseket.

**Comment by UnknownPlayer78** [comment]
Ez a funkcio jelenleg csak akkor mukodik ha a beallitasokban kikapcsolod a html renderelest
ezzel elveszik a szoveg formazasa de automatikusan megtalalja a linkeket es kijelolheto lesz a szoveg
kesobb lehet hogy ez lesz az alapbeallitas, meg nem vagyunk benne biztosak melyik lenne a legjobb megoldas

**Comment by stsmurfy** [comment]
> Ez a funkcio jelenleg csak akkor mukodik ha a beallitasokban kikapcsolod a html renderelest
> ezzel elveszik a szoveg formazasa de automatikusan megtalalja a linkeket es kijelolheto lesz a szoveg
> kesobb lehet hogy ez lesz az alapbeallitas, meg nem vagyunk benne biztosak melyik lenne a legjobb megoldas

Szuper. Nem értettem mire való az a gomb. Vmi jobb nevet kéne adni, mert így nem világos mit csinál és hol. De a Kréta html formázást is csinál és kijelölhető is. Vmi ilyesmi irányt kéne venni és akkor nincs szükség gombra.

**Comment by RedyAu** [comment]
Amikor lesz package, akkor az anélküli rendert akár ki is lehet venni, addig is. Well. :/
