### ISSUE TITLE
App gyorsgombok

### ISSUE THREAD

**Issue by 55nknown** [filc/naplo#48]
Minden egyes oldalhoz egy külön gyorsgomb.

![image](https://user-images.githubusercontent.com/55922348/135757725-4c6f1e9a-5b3c-4b77-b42c-575a9c443319.png)

https://pub.dev/packages/quick_actions
https://developer.android.com/guide/topics/ui/shortcuts
https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/home-screen-actions/

**Comment by ezyyeah** [comment]
done
