### ISSUE TITLE
Oldalakra kattintás végigpörgeti a füleket...

### ISSUE THREAD

**Issue by thegergo02** [filc/naplo#5]
...az első fülig, ha már ugyanazon az oldalon vagyok.

**Comment by 55nknown** [comment]
füleket? 😄

**Comment by thegergo02** [comment]
*tabszerűcuccok :smile:

**Comment by 55nknown** [comment]
tudsz küldeni esetleg videót?

**Comment by thegergo02** [comment]
Példa: Absences oldalon vagyok, rámegyek az utolsó tabra (Misses), rányomok alul újra az absences oldalra és végigmegy gyorsan a Misses, Delays majd Absences tabra.

**Comment by 55nknown** [comment]
Érdekes, nekem csak simán átugrik az első tabra (egyébként filtereknek hívjuk)

**Comment by thegergo02** [comment]
@55nknown Ha sikerül felvennem valahogy idejuttatom

**Comment by 55nknown** [comment]
Azt tudom felajánlani, hogyha már a tabon vagy, nem tölti újra és akkor nem is fog ugrálni.

**Comment by 55nknown** [comment]
fixed
