### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by 55nknown** [filc/naplo#50]
https://pub.dev/packages/dart_discord_rpc

**Comment by PiciAkk** [comment]
tokent kéne rakni az alkalmazásba, nem baj ez?

**Comment by DarK-rtfm** [comment]
Appid kell, az egy nyilvános ID, ami az alkalmazásra készült discord cuccot azonosítja. Tehát nem baj

**Comment by 55nknown** [comment]
> tokent kéne rakni az alkalmazásba, nem baj ez?
> 

Kedves Kicsi Akk!

Helyesen rávilágított arra, hogy ez egy óriási veszélyt rejt. Ezért nem létezik még egyetlen Discord RPC-t hasznosító megoldás se. Akik megpróbálkoztak ezzel, mind fel lettek törve és a tokenen keresztül ellopták az összes pénzüket. Mi borsodiként nem rendelkezünk pénzzel, így ez minket nem fenyeget. Más biztonsági kockázat miatt cégünk nem vállalna egy ilyen kockázatot. Annyira nem kockáztatunk, hogy meg se nézzük a hivatalos Discord dokumentációt, mely szerint az Application ID nyilvánosan megosztható és a token-re csak szerveroldalon lenne szükség.
Köszönjük, hogy szakértelmével védi a Filc felhasználóbázisát. Elismerésünk jeléül a bug bounty program keretében százötvennégyezer-háromszáztizenöt forintot adományozunk Önnek.

Üdvözlettel,
eFilc Informatikai Zrt. Ügyfélszolgálat

**Comment by RedyAu** [comment]
*Százötvennégyezer-háromszáztizenöt tized fillért

**Comment by PiciAkk** [comment]
Kedves Ügyfélszolgálat!

Köszönöm ismét a tisztelt Ügyfélszolgálat válaszát! A válaszomat tényleg nem előzte meg kellő mértékű utánanézés, ezért elnézésüket kérem! 

Üdv!
