### ISSUE TITLE
Mellékletek megjelenítése/letöltése

### ISSUE THREAD

**Issue by StokiBoti** [filc/naplo#76]
A képeken látható, hogy a Krétában megjelnik a csatolt fájl(ok), de a Filc valamiért ugyanannál a házi feladatnál nem mutatja.
![Screenshot_20201114-210952](https://user-images.githubusercontent.com/68708769/99156071-74ca7880-26be-11eb-8a5c-70e9001fd2ab.jpg)
![Screenshot_20201114-211127_KRTA Tanulknak](https://user-images.githubusercontent.com/68708769/99156072-75630f00-26be-11eb-99ae-c662a57ebdda.jpg)

**Comment by DarK-rtfm** [comment]
https://github.com/filc/naplo/issues/37 duplikált
