### ISSUE TITLE
Órarend menü egy napot nem jelez!

### ISSUE THREAD

**Issue by Empire201** [filc/naplo#8]
Sziasztok!

Nem jelzi az órarend a keddi napot! Csatolok kép megosztó linket!

[https://drive.google.com/file/d/1WUWxQVIwq2vfaPl1kavYaMaXdk0dQTzN/view?usp=drivesdk](url)

Jó lesz ez az app! Gratulálok! Jó programozó Unknown!!

Üdvözlettel:
Empire201

**Comment by Zateros** [comment]
Ez a tanárok hibája, valószínűleg kimaradt az a nap. Nézd meg, hogy a webes felületen is úgy van-e.

**Comment by Empire201** [comment]
> Ez a tanárok hibája, valószínűleg kimaradt az a nap. Nézd meg, hogy a webes felületen is úgy van-e.

Keddre nem tettek be semmit de ha nem változik hogy ha betettek órát jelzem másik Issuessal.

**Comment by DarK-rtfm** [comment]
Ne csinálj másikat, nyisd meg ezt újra ha utána sem lesz..

**Comment by Empire201** [comment]
> Ne csinálj másikat, nyisd meg ezt újra ha utána sem lesz..

Megoldódott! Köszönöm
