### ISSUE TITLE
Eltűnt a péntek

### ISSUE THREAD

**Issue by csumpasd** [filc/naplo#82]
az órarend lapon csak négy napot látok, hiányzik a péntek. Próbáltam leállítani az appot, és törölni a gyorsítótárat, nem segített. Mi lehet itt a megoldás? Köszönöm a segítséget :)
![Screenshot_2020-12-03-10-52-50-63.jpg](https://user-images.githubusercontent.com/45290377/100993594-e5deac80-3555-11eb-9246-4adcb0745452.jpg)

**Comment by UnknownPlayer78** [comment]
Köszönjük a hibajelentést, már tudunk a problémáról. A következő frissítésben várható a javítás. (1 héten belül)

**Comment by RedyAu** [comment]
Javítva
