### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by notramo** [filc/naplo#85]
https://f-droid.org

**Comment by RedyAu** [comment]
Köszönjük az ötletet, de erről nincs értelme issue-t nyitni.
Egyelőre megpróbálunk visszakerülni Playre.

**Comment by notramo** [comment]
@RedyAu Nem a Play issue miatt.
Vannak olyan telefonok, amin egyáltalán nincs Play:
  - új Huawei
  - LineageOS

**Comment by Balint66** [comment]
Arra ott van a microG és az Aurora Store.
De valóban, az F-Droid egy jó megoldás, de perpillanat a Play Áruházos probláma prioritást élvez.

**Comment by notramo** [comment]
Más fejlesztők mindent megtesznek, csakhogy minnél több helyen legyen elérhető az app. Sok appot már az AppGalery-be is feltöltöttek.

**Comment by Balint66** [comment]
Ez tény, de most olyan gonddal állnak a fejlesztők szembe, ami lehetséges, hogy a többi áruháztól is el lehetetleníti őket, kivéve az F-Droidból, persze, főleg ha saját szervert futtatnak.
Ám kérlek, légy türelemmel, mivel ez is fent van a listán, de mind mondtuk, a Play Áruház, és ezzel más áruházak problémája priorítást élvez.

**Comment by Balint66** [comment]
@notramo A filces F-Droid tároló most már elérhető [https://filcnaplo.hu/fdroid/repo/](https://filcnaplo.hu/fdroid/repo/) oldalon. :)

**Comment by notramo** [comment]
https://filcnaplo.hu/dmca/ Itt azt írja, hogy még nem.

**Comment by UnknownPlayer78** [comment]
Tulajdonkeppen meg teszt fazisban van de amint veglegesitjuk, kiirjuk oda is.

**Comment by Balint66** [comment]
A Discordon már kirakták a fejlesztők, hogy lehet tesztelni, és hogy ott lesz, gondoltam szólok.
