### ISSUE TITLE
Ghost grade error

### ISSUE THREAD

**Issue by thegergo02** [filc/naplo#85]
![](https://i.imgur.com/yv9Qj6q.jpg)
![](https://i.imgur.com/6xnTotM.jpg)
![](https://i.imgur.com/i0AbQqk.jpg)
![](https://i.imgur.com/5liHoRu.jpg)
![](https://i.imgur.com/eGO4NpY.jpg)
![](https://i.imgur.com/4Q3pe6Y.jpg)

**Comment by thegergo02** [comment]
Ebben a verzióban jött be.

**Comment by DarK-rtfm** [comment]
Szia! Tudunk róla, következő kiadásban javítva lesz :)
