### ISSUE TITLE
BUG: Amikor lezárul a képernyő, ha újra feloldom, az alkalmazás fekete képernyőt mutat

### ISSUE THREAD

**Issue by d4f5409d** [filc/naplo#89]
Pár napja történik ilyen OxygenOS-en. ![Screenshot_20220118-143317.jpg](https://user-images.githubusercontent.com/76624594/149947525-dcb67f48-8655-438f-ba68-c1a63ce303a4.jpg)![Screenshot_20220118-143314.jpg](https://user-images.githubusercontent.com/76624594/149947537-e6dc11ef-5208-4797-a61a-4ee9eaea82ad.jpg)

**Comment by 55nknown** [comment]
En nem tudtam reprodukalni, de lehet hogy eleg vendor/os version specific

**Comment by ezyyeah** [comment]
Igen OxygenOS en nalam is ez a helyzet, mas platformon nem nagyon fordult elo.
quick fix: lerakod hatterbe, utanna visszahozod, megoldja mindig.

**Comment by d4f5409d** [comment]
> Igen OxygenOS en nalam is ez a helyzet, mas platformon nem nagyon fordult elo.
> quick fix: lerakod hatterbe, utanna visszahozod, megoldja mindig.

Igen igen már én is próbáltam de azért köszi
