### ISSUE TITLE
bepakolas segito

### ISSUE THREAD

**Issue by 55nknown** [filc/naplo#94]
este szoktam bepakolni es mindig hosszu perceket toltok azzal, hogy kilogikazzam, hogy a kovetkezo napra milyen fuzeteket/konyveket kell bepakolnom

**Comment by d4f5409d** [comment]
Wtf
Csak megnézed az órarendet

**Comment by DarK-rtfm** [comment]
Realisabban nem is pakolsz, ami kell mar iskolaban van szekrenyedben, ha nem adnak szekrenyt akkor meg nem erdemlik meg, hogy felszerelessel ulj be orara.

**Comment by 55nknown** [comment]
kidobtam az osszes fuzetem lol
