### ISSUE TITLE
Subject average bug

### ISSUE THREAD

**Issue by Xeretis** [filc/naplo#96]
A tantárgyi átlag kiszámításánál olyan tantárgyak is beleszámítanak a tárgyak össz számába, amikhez nem tartozik jegy. Pl.: Magatartás, Szorgalom

Emiatt nem valós eredményt ad a bal alsó tantárgyi átlag kártya a jegyek oldalon.

**Comment by bru02** [comment]
Köszi a hibajelentést!

Már javítva van [itt](https://github.com/filc/mobile/commit/89da286f838647e60fdf2ad9c29aa011e25c57ea), kövi frissítésben már jó lesz.
